/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package de.htw.saarland.gamedev.nap.mapeditor;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;

/**
 *
 * @author Pascal
 */
public class MapEditor extends javax.swing.JFrame {

    private JLabel[][] mapTiles;
    
    /**
     * Creates new form MapEditor
     */
    public MapEditor() {
        initComponents();
        
        buildPalette(2);
        buildMap(100, 10);
    }
    
    private void buildPalette(int columns) {
        // TODO fill with correct palette
        int tileCount = 10;
        
        panelPalette.removeAll();
        
        GridLayout layout = (GridLayout)panelPalette.getLayout();
        layout.setColumns(columns);
        layout.setRows((int)Math.ceil((double)tileCount / (double)columns));
        
        for (int i = 0; i < tileCount; i++) {
            final JLabel tmp = new JLabel(Integer.toString(i));
            tmp.setPreferredSize(new Dimension(96, 96));

            tmp.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseEntered(MouseEvent e) {
                    tmp.setBorder(new LineBorder(Color.BLACK, 1));
                }
                @Override
                public void mouseExited(MouseEvent e) {
                    tmp.setBorder(null);
                }
            });

            panelPalette.add(tmp);
        }
        
        panelPalette.revalidate();
    }
    
    private void buildMap(int width, int height) {
        mapTiles = new JLabel[height][width];
        
        panelMap.removeAll();
        
        GridLayout layout = (GridLayout)panelMap.getLayout();
        layout.setColumns(width);
        layout.setRows(height);
        
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                final JLabel tmp = new JLabel(i + "," + j);
                tmp.setPreferredSize(new Dimension(96, 96));
                mapTiles[i][j] = tmp;
                
                mapTiles[i][j].addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseEntered(MouseEvent e) {
                        tmp.setBorder(new LineBorder(Color.BLACK, 1));
                    }
                    @Override
                    public void mouseExited(MouseEvent e) {
                        tmp.setBorder(null);
                    }
                });
                
                panelMap.add(mapTiles[i][j]);
            }
        }
        
        panelMap.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelMap = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelPalette = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemSetSize = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuItemSave = new javax.swing.JMenuItem();
        menuItemLoad = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        panelMap.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(panelMap);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelPalette.setLayout(new java.awt.GridLayout());
        jScrollPane2.setViewportView(panelPalette);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.EAST);

        jMenu1.setText("File");

        menuItemSetSize.setText("Size");
        menuItemSetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSetSizeActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSetSize);
        jMenu1.add(jSeparator1);

        MenuItemSave.setText("Save");
        jMenu1.add(MenuItemSave);

        menuItemLoad.setText("Load");
        jMenu1.add(menuItemLoad);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSetSizeActionPerformed
        String sWidth = JOptionPane.showInputDialog(this, "Type in a width", 100);
        String sHeight = JOptionPane.showInputDialog(this, "Type in a height", 100);
        
        try {
            int width = Integer.parseInt(sWidth);
            int height = Integer.parseInt(sHeight);

            buildMap(width, height);
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Width or height was invalid", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_menuItemSetSizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuItemLoad;
    private javax.swing.JMenuItem menuItemSetSize;
    private javax.swing.JPanel panelMap;
    private javax.swing.JPanel panelPalette;
    // End of variables declaration//GEN-END:variables
}
