/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.htw.saarland.gamedev.nap.launcher;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;
import sfs2x.client.SmartFox;
import sfs2x.client.entities.Room;
import sfs2x.client.entities.User;

/**
 *
 * @author Bea
 */
public class FrameLauncher extends javax.swing.JFrame {

    private SmartFox sfClient;
    
    /**
     * Creates new form FrameLauncher
     */
    public FrameLauncher(SmartFox sfClient) {
        this.sfClient = sfClient;
        
        initComponents();
    }
    
    public void messageReceived(final String from, final String text) {
        final SimpleDateFormat formatter = new SimpleDateFormat("HH:mm");
        
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
                textAreaChatLog.setText(textAreaChatLog.getText() + 
                        "[" + formatter.format(new Date(System.currentTimeMillis())) + "] " +
                        from + ": " + text + "\n");
            }
        });
    }
    
    public void roomJoined(Room room) {
        // TODO implement
    }
    
    
    public void userEnteredRoom(User user, Room room) {
        // TODO
    }
    
    public void userLeftRoom(User user, Room room) {
        // TODO
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        InfoPanel = new javax.swing.JPanel();
        ContentPanel = new javax.swing.JPanel();
        MatchSelectorPanel = new javax.swing.JPanel();
        MatchSelectorButtonPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listRooms = new javax.swing.JList();
        ChatAndSettingsPanel = new javax.swing.JPanel();
        SettingsButtonPanel = new javax.swing.JPanel();
        ChatPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaChatLog = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        MainPanel.setLayout(new java.awt.BorderLayout());

        InfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        InfoPanel.setMinimumSize(new java.awt.Dimension(100, 30));

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        MainPanel.add(InfoPanel, java.awt.BorderLayout.NORTH);

        ContentPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout ContentPanelLayout = new javax.swing.GroupLayout(ContentPanel);
        ContentPanel.setLayout(ContentPanelLayout);
        ContentPanelLayout.setHorizontalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        ContentPanelLayout.setVerticalGroup(
            ContentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );

        MainPanel.add(ContentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        MatchSelectorPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MatchSelectorPanel.setMinimumSize(new java.awt.Dimension(150, 450));
        MatchSelectorPanel.setPreferredSize(new java.awt.Dimension(150, 450));
        MatchSelectorPanel.setLayout(new java.awt.BorderLayout());

        MatchSelectorButtonPanel.setPreferredSize(new java.awt.Dimension(150, 100));
        MatchSelectorButtonPanel.setLayout(new java.awt.BorderLayout());
        MatchSelectorPanel.add(MatchSelectorButtonPanel, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listRooms.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listRooms);

        MatchSelectorPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(MatchSelectorPanel, java.awt.BorderLayout.EAST);

        ChatAndSettingsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ChatAndSettingsPanel.setMinimumSize(new java.awt.Dimension(800, 150));
        ChatAndSettingsPanel.setPreferredSize(new java.awt.Dimension(800, 150));
        ChatAndSettingsPanel.setLayout(new java.awt.BorderLayout());

        SettingsButtonPanel.setMinimumSize(new java.awt.Dimension(150, 100));
        SettingsButtonPanel.setPreferredSize(new java.awt.Dimension(150, 146));
        SettingsButtonPanel.setLayout(new java.awt.BorderLayout());
        ChatAndSettingsPanel.add(SettingsButtonPanel, java.awt.BorderLayout.EAST);

        ChatPanel.setLayout(new java.awt.BorderLayout());

        jTextField1.setText("jTextField1");
        jTextField1.setMinimumSize(new java.awt.Dimension(6, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(59, 25));
        ChatPanel.add(jTextField1, java.awt.BorderLayout.SOUTH);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        textAreaChatLog.setEditable(false);
        textAreaChatLog.setColumns(20);
        textAreaChatLog.setLineWrap(true);
        textAreaChatLog.setRows(5);
        jScrollPane2.setViewportView(textAreaChatLog);

        jPanel9.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setMinimumSize(new java.awt.Dimension(150, 24));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(150, 4));

        listUsers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listUsers);

        jPanel9.add(jScrollPane3, java.awt.BorderLayout.EAST);

        ChatPanel.add(jPanel9, java.awt.BorderLayout.CENTER);

        ChatAndSettingsPanel.add(ChatPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(ChatAndSettingsPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChatAndSettingsPanel;
    private javax.swing.JPanel ChatPanel;
    private javax.swing.JPanel ContentPanel;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MatchSelectorButtonPanel;
    private javax.swing.JPanel MatchSelectorPanel;
    private javax.swing.JPanel SettingsButtonPanel;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList listRooms;
    private javax.swing.JList listUsers;
    private javax.swing.JTextArea textAreaChatLog;
    // End of variables declaration//GEN-END:variables
}
